blog/urls.py
from django.urls import path
from .feed import LatestPostFeed
from . import views



app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search', views.post_serach, name="post_search"),
]

learningDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', views.home, name='home_page'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls', namespace='account')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                            choices=STATUS_CHOICES,
                            default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

class ActivatedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField("Urzytkownik", max_length=80)
    email = models.EmailField("Email")
    body = models.TextField("Treść komentarza")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    activated = ActivatedManager()
    objects= models.Manager()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarsz dodany przez {} dla posta {}'.format(self.name, self.post)

    def get_absolute_url(self):
        return Post.published.get(id=self.post_id).get_absolute_url()

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                             widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    choices = (
        ('1', 'body and title(trigramSimilarity)'),
        ('2', 'only title(searchVector)'),
    )
    which_search_engine = forms.ChoiceField(label="Po czym wyszukać?",
                                            choices=choices)
    query = forms.CharField(label="Treść zapytania:",
                            widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


def post_serach(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            if form.cleaned_data['which_search_engine'] == '2':
                #trygramsearcher
                query = form.cleaned_data['query']
                results = Post.objects.annotate(similarity=TrigramSimilarity('title', query),).filter(similarity__gt=0.1).order_by('-similarity')
            else:
                #advanced search query with weight
                query = form.cleaned_data['query']
                search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
                search_query = SearchQuery(query)
                results = Post.objects.annotate(search=search_vector,rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.3).order_by('-rank')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request,year,month,day,post):
    post = get_object_or_404(Post, slug=post,
                           status='published',
                           publish__year=year,
                           publish__month=month,
                           publish__day=day)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts })


def post_share(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) zachęca do przeczytania "{}'.format(cd['name'], cd['email'], post.title)
            message = 'Przeczytaj "{}" na stronie {}\n\n Komentarz dodany przez {}: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'learndjangobybombo@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',{'post': post,
                                                   'form': form,
                                                   'sent': sent})

blog/templates/blog/post/detail.html
{% extends "blog/blog_base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags  %}

{% block title %}{{ post.title }}{% endblock %}

{% block content2 %}


{# showing post   #}
  <h1>{{ post.title }}</h1>
    <p>
        <h10> Tagi:
            {% for tag in post.tags.all %}
                <a href="{%  url "blog:post_list_by_tag" tag.slug %}" %}>
                    {{ tag.name }}
                </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </h10>
    </p>

  <p>
    Opublikowany {{ post.publish }} przez {{ post.author }}
  </p>
  {{ post.body|markdown }}
    <p>
        <a href = "{% url "blog:post_share" post.id %}" class="btn btn-dark">
            Udostępnij post
        </a>
    </p>

{# similar posts #}
    <h2>Podobne posty:</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Nie ma podobnych postów
    {% endfor %}

{# comments section #}
    {% with  comments.count as total_comments %}
        <h2>
            {{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}
        </h2>
    {% endwith %}

{# list of comments  #}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}{# author of comment #}
                {{ comment.created }} {# date of comment #}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {#if there is no comments  #}
        {% empty %}
            <p>
                Nie ma jeszcze żadnych komentarzy
            </p>
    {% endfor %}


{# form for new comment  #}
    {%  if new_comment %}
        <h2>Twój komentarz został dodany.</h2>
    {% else %}
        <h2>Dodaj nowu komentarz</h2><br>
        <div class="form-row">
            <form action="." method="post">
                {{ comment_form|crispy }}
                {% csrf_token %}
                <p>
                    <input type="submit" value="Dodaj komentarz" class="btn btn-primary">
                </p>
            </form>
        </div>
    {%  endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul class="nav flex-column">
    <li class="nav-item">
        Ostatnie posty:
    </li>
    {% for post in latest_post %}
        <li class="nav-item">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/blog_base.html" %}
{% load blog_tags %}

{% block title %}Mój Blog{% endblock %}

{% block content2 %}
    <h1>Blog by Bombo</h1>
    <p >
        Szukasz posta? Sprawdź wyszukiwarke <br>
        <a class="btn btn-primary" href="{% url "blog:post_search" %}">SEARCH</a>
    </p>

    {% if tag %}
        <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
    <div class="card">
        <!--<img src="..." class="card-img-top" alt="...">-->
        <div class="card-body">
            <a href="{{ post.get_absolute_url }}">
                <h5 class="card-title">{{ post.title }}</h5>
            </a>
            <p>
              <h10> Tagi:
              {% for tag in post.tags.all %}
                  <a href="{%  url "blog:post_list_by_tag" tag.slug %}" %}>
                    {{ tag.name }}
                  </a>
                  {% if not forloop.last %}, {% endif %}
              {% endfor %}
              </h10>
            </p>
            <p>
                Opublikowany {{ post.publish }} przez {{ post.author }}
            </p>
            <p class="card-text">
                <span class="placeholder" style="width: 25%;"></span>
                {{ post.body|markdown|truncatewords_html:30 }}
            </p>

        </div>
    </div>
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/blog_base.html" %}
{% load crispy_forms_tags  %}
{% load blog_tags %}
{% block title %}Wyszukaj{% endblock %}

{% block content2 %}
    {% if query %}
        <h1>Posty zawierające "{{ query }}"</h1>
        <h3>Znaleziono "{% len_of results %}" wynik{{ results|pluralize:"ów" }}</h3>
        <br>
        {% for result in results %}
            <h4><a href="{{ result.get_absolute_url }}">{{ result.title }}</a></h4>
        {% empty %}
            <p>
                Brak wyników dla podanego wyszukania.
            </p>
        {% endfor %}
        <p>
            <br>
            <a href="{% url "blog:post_search" %}">Szukaj ponownie</a>
        </p>
    {% else %}
        <h1>Szukaj postów</h1>
        <div class="form-row">
        <form method="get" >
            {{ form|crispy }}
            <input type="submit" value="Szukaj" class="btn btn-primary">
        </form>
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/blog_base.html" %}
{% load crispy_forms_tags  %}
{% block title %}Udostępnij post{% endblock %}

{% block content2 %}
  {% if sent %}
    <h1>E-mail pomyślnie wysłano</h1>
    <p>
      "{{ post.title }}" pomyślnie wysłano do {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
    <form method="post">
      {{ form|crispy }}
      {% csrf_token %}
      <input type="submit" value="Wyślij e-mail">
    </form>
  {% endif %}
{% endblock %}