account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('SOCIAL/', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change', auth_views.PasswordChangeView.as_view(), name='pasword_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

blog/urls.py
from django.urls import path
from .feed import LatestPostFeed
from . import views



app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search', views.post_serach, name="post_search"),
]

learningDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', views.home, name='home_page'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls', namespace='account')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body >
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url "home_page" %}">LearningDjango</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "blog:post_list" %}">BLOG APP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/sitemap.xml">SOCIAL APP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/admin/">ADMIN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/sitemap.xml">sitemap.xml</a>
        </li>

        <span>
            {% if requst.user.is_authenticated %}
                Witaj, {{ request.user.first_name }}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:logout" %}">Wyloguj się</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:dashboard" %}">Dashboard</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:login" %}">Zaloguj się</a>
                </li>
            {% endif %}
        </span>
    </ul>

    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>